/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sinus2;

import java.awt.Color;
import java.awt.Graphics;

/**
 *
 * @author Michał
 */
public class Sinus2Panel extends javax.swing.JPanel {
int suwakAmpl=50;
int suwakSklStala=300;
int suwakczestosc=50;
    
    public Sinus2Panel() {
        initComponents();
    }
    
    
 //@Override
 public void paintComponent(Graphics g) {
                g.setColor(Color.cyan);         //teraz rozumie jeden obiekt g typu Graphics 
		g.fillRect(-1,-1,1500, 1500);
                
                g.setColor(Color.red);
                
                int x = 0 ;
                int y;
                
                 while(x<=1500){
                    
                    double xx = (double) x;
                    double yy = suwakSklStala + suwakAmpl*Math.sin(xx/suwakczestosc);
                    x = (int)xx;
                    y = (int)yy;
                    g.fillOval(x, y, 5, 5);
                    x++;
                 }
                    repaint();
	}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        suwakAmplituda = new javax.swing.JSlider();
        suwakOffset = new javax.swing.JSlider();
        suwakOmega = new javax.swing.JSlider();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        suwakAmplituda.setMaximum(300);
        suwakAmplituda.setMinimum(10);
        suwakAmplituda.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                suwakAmplitudaStateChanged(evt);
            }
        });

        suwakOffset.setMaximum(500);
        suwakOffset.setMinimum(10);
        suwakOffset.setValue(300);
        suwakOffset.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                suwakOffsetStateChanged(evt);
            }
        });

        suwakOmega.setMaximum(300);
        suwakOmega.setMinimum(5);
        suwakOmega.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                suwakOmegaStateChanged(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton1.setText("Lisajux");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setText("amplituda: A");

        jLabel2.setText("wysokość: H");

        jLabel3.setText("częstość: f");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(22, 22, 22))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(suwakAmplituda, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 124, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(suwakOffset, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(109, 109, 109)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(suwakOmega, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 411, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(suwakOffset, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(suwakAmplituda, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(suwakOmega, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void suwakAmplitudaStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_suwakAmplitudaStateChanged
        suwakAmpl = suwakAmplituda.getValue();
    }//GEN-LAST:event_suwakAmplitudaStateChanged

    private void suwakOffsetStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_suwakOffsetStateChanged
        suwakSklStala = suwakOffset.getValue();
    }//GEN-LAST:event_suwakOffsetStateChanged

    private void suwakOmegaStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_suwakOmegaStateChanged
      suwakczestosc = suwakOmega.getValue();
    }//GEN-LAST:event_suwakOmegaStateChanged

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        LissFrame lisajux = new LissFrame();
        lisajux.setVisible(true);
        lisajux.setLocationRelativeTo(null);
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JSlider suwakAmplituda;
    private javax.swing.JSlider suwakOffset;
    private javax.swing.JSlider suwakOmega;
    // End of variables declaration//GEN-END:variables
}
